# -*- coding: utf-8 -*-
"""Time series Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/132mHW51k6xoN6mKaxJkNnnkB2YoVvR-2
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import folium
import seaborn as sns

data = pd.read_csv("/content/drive/MyDrive/sem9/sem9/typhoon_data.csv", index_col=0)
info = pd.read_csv("/content/drive/MyDrive/sem9/sem9/typhoon_info.csv", index_col=0)

print(info.shape)
info.sample(5)

print(len(data["International number ID"].unique()))

vc = data["International number ID"].value_counts()
print(vc)
print(np.mean(vc))

info.info()

data.info()

data[data["Maximum sustained wind speed"].isna()]

data[25268:].info()

data[25277:25283]

data[data["Direction of the longest radius of 50kt winds or greater"].isna()]["grade"].unique()

data[data["Direction of the longest radius of 50kt winds or greater"].notna()]["grade"].unique()

data[data["year"] < 1977]["grade"].unique()

data[data["year"] >= 1977]["grade"].unique()

data = data[data["year"] >= 1977]
data.info()

print(data[data["Direction of the longest radius of 50kt winds or greater"].notna()]["grade"].unique())
print(data[data["Direction of the longest radius of 50kt winds or greater"].isna()]["grade"].unique())

typhoons = data["International number ID"].unique() # Unique IDs of typhoons
info[info["Name"].str.strip() == "MAEMI"]

maemi_data = data.copy()[data["International number ID"]==314]
maemi_data

maemi_data[30:35]

maemi_data["Elapsed Hour"] = (maemi_data["day"]-4)*24 + maemi_data["hour"]
maemi_data.head()

maemi_data = maemi_data.drop(["International number ID", "year", "month", "day", "hour"], axis=1)
maemi_data.head()

maemi_data["Longitude of the center"] /= 10
maemi_data["Latitude of the center"] /= 10

fig = plt.figure(figsize=(3,3))
plt.xlim(120, 170)
plt.ylim(5, 55)
plt.plot(maemi_data["Longitude of the center"], maemi_data["Latitude of the center"], "red")
plt.show()

scale = maemi_data["The longeast radius of 30kt winds or greater"].fillna(60)
fig = plt.figure(figsize=(5,5))
plt.xlim(120, 170)
plt.ylim(5, 55)
plt.plot(maemi_data["Longitude of the center"], maemi_data["Latitude of the center"], "black", linewidth=1)
plt.scatter(maemi_data["Longitude of the center"], maemi_data["Latitude of the center"], s=scale/3, c=maemi_data["Maximum sustained wind speed"])
plt.show()

# Color map
import matplotlib as mpl
import matplotlib.cm as cm

c = maemi_data.copy()["Maximum sustained wind speed"]
cmap = cm.jet

def rgb_to_hex(rgb):
    return '#%02x%02x%02x' % rgb
m = folium.Map(location=[38.9, 153.2], zoom_start=3, width=600, height=600)
for i in range(len(maemi_data)):
    color = cmap(c.iloc[i]/c.max())
    color = tuple([int(c*255) for c in color[:3]])
    color = rgb_to_hex(color)
    folium.Circle(location=[maemi_data.iloc[i]["Latitude of the center"], maemi_data.iloc[i]["Longitude of the center"]],
                 radius=scale.iloc[i]*1852,  #  nautical mile to meter
                 fill=True,
                 color="black",
                 fill_color=color).add_to(m)
m

plt.title("Typhoon's Central Pressure in hPa")
plt.plot(maemi_data["Elapsed Hour"],maemi_data["Central pressure"])
plt.xlabel("Elapsed Hour")
plt.ylabel("Central Pressure")
plt.legend()
plt.show()

plt.title("Typhoon's Wind Speed in knot(kt)")
plt.plot(maemi_data["Elapsed Hour"],maemi_data["Maximum sustained wind speed"])
plt.xlabel("Elapsed Hour")
plt.ylabel("Maximum sustained wind speed")
plt.legend()
plt.show()